- name: Install git
  apt: update_cache=yes name={{item}} state=present
  with_items:
  - git

- name: Clone hl
  git: repo=git://github.com/haskell-infra/hl.git dest=/srv/web/hl accept_hostkey=yes

- name: Submodules
  command: chdir=/srv/web/hl git submodule update --init

# TODO: Figure out how to nuke the annoying PATH stuff
- name: Update cabal cache
  shell: chdir=/srv/web/hl PATH="$PATH:/opt/ghc/7.8.3/bin/:/opt/cabal/1.20/bin/" cabal update

- name: Create a cabal sandbox
  shell: chdir=/srv/web/hl PATH="$PATH:/opt/ghc/7.8.3/bin/:/opt/cabal/1.20/bin/" cabal sandbox init

# This will error out if already installed in the sandbox, so ignore_errors.
- name: Install happy
  shell: chdir=/srv/web/hl PATH="$PATH:/opt/ghc/7.8.3/bin/:/opt/cabal/1.20/bin/" cabal install happy
  ignore_errors: True

# This will error out if already installed in the sandbox, so ignore_errors.
- name: Install alex
  shell: chdir=/srv/web/hl PATH="$PATH:/opt/ghc/7.8.3/bin/:/opt/cabal/1.20/bin/" cabal install alex
  ignore_errors: True

- name: Clear static files cache
  command: chdir=/srv/web/hl touch src/HL/Static.hs

- name: Install hl
  shell: chdir=/srv/web/hl PATH="$PATH:/opt/ghc/7.8.3/bin/:/opt/cabal/1.20/bin/" cabal install

- name: Install upstart script
  copy: src=hl.conf dest=/etc/init/hl.conf

- name: Configure nginx
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  tags:
  - nginx

- name: (re)start nginx
  service: name=nginx state=restarted
  tags:
  - nginx

- name: Start hl (and at boot)
  service: name=hl state=restarted enabled=yes
