- name: Install nrpe and nagios plugins ({{item}})
  apt: state=present pkg={{item}}
  with_items:
  - nagios-nrpe-server
  - nagios-plugins-basic

- name: Create directory for nrpe config
  file: path=/etc/nagios state=directory

- name: Sync nrpe template
  template: src=nrpe.cfg dest=/etc/nagios/nrpe.cfg

- name: Copy custom plugins
  copy: src=plugins/ dest=/usr/lib/nagios/plugins/ mode=0755

- name: Enable and restart nrpe to load new config
  service: name=nagios-nrpe-server enabled=yes state=restarted

- name: Create directory for host info on nagios host
  file: path=/etc/nagios/hosts state=directory
  delegate_to: monitor.haskell.org

- name: Inform nagios about the new node
  template: src=hosts/{{inventory_hostname}}.cfg dest=/etc/nagios/hosts/{{inventory_hostname}}.nrpe.cfg mode=0644
  delegate_to: monitor.haskell.org

- name: Delete the non-nrpe nagios template, if it exists
  file: name=/etc/nagios/objects/non-nrpe-hosts/{{inventory_hostname}}.cfg state=absent
  delegate_to: monitor.haskell.org

- name: Rehash nagios
  service: name=nagios enabled=yes state=reloaded
  delegate_to: monitor.haskell.org
