- name: Get haskell-infra copr repo
  get_url: url=http://copr.fedoraproject.org/coprs/codeblock/haskell-infra/repo/epel-6-x86_64/ dest=/etc/yum.repos.d/haskell-infra.repo mode=0644

- name: Install nagios + deps ({{item}})
  yum: state=installed pkg={{item}}
  with_items:
  - nagios
  - nagios-plugins-all
  - nagios-plugins-nrpe # Why isn't this in -all?
  - php-fpm
  - perl-FCGI
  - supervisor # for HaskNag bot
  - hasknag    # for HaskNag bot
  - nc         # for HaskNag bot

- name: Copy main config
  copy: src=nagios.cfg dest=/etc/nagios/nagios.cfg

- name: Copy object config ({{item}})
  copy: src={{item}} dest=/etc/nagios/objects/{{item}}
  with_items:
  - hostgroups.cfg
  - commands.cfg
  - contacts.cfg
  - timeperiods.cfg
  - templates.cfg

- name: Copy locally run actions
  copy: src=local-checks/ dest=/etc/nagios/objects/local-checks

- name: Copy non-NRPE host configs
  copy: src=non-nrpe-hosts/ dest=/etc/nagios/objects/non-nrpe-hosts

- name: Configure nagios service
  service: name=nagios state=started enabled=yes

- name: Copy supervisord config
  copy: src=supervisord.conf dest=/etc/supervisord.conf

- name: Configure supervisord service
  service: name=supervisord state=started enabled=yes

- name: Set up php-fpm
  copy: src=php-fpm.conf dest=/etc/php-fpm.d/www.conf

- name: Install perl fcgi wrapper script
  copy: src=fastcgi-wrapper.pl dest=/usr/local/bin/fastcgi-wrapper.pl mode=0755

- name: Add perl fcgi wrapper script to upstart
  copy: src=fastcgi-wrapper.conf dest=/etc/init/fastcgi-wrapper.conf

- name: Configure nginx for nagios
  copy: src=nagios-nginx.conf dest=/etc/nginx/nginx.conf
  tags:
  - nginx

- name: Make sure the htpasswd file is readable by nginx
  command: chown root.nginx /etc/nagios/passwd
  tags:
  - nginx

- name: Restart nginx
  command: service nginx reload
  tags:
  - nginx

- name: Start fastcgi-wrapper
  command: start fastcgi-wrapper

- name: Check for dd-agent user
  shell: getent passwd | grep -q dd-agent
  register: ddagent
  ignore_errors: true

- name: Add dd-agent to nagios group
  user: name=dd-agent groups=nagios append=yes
  when: ddagent|success

- name: Make sure apache is disabled
  service: name=httpd state=stopped enabled=no
