- name: Gather monitor.haskell.org facts
  hosts: monitor.haskell.org
  user: "{% if cloud == 'true' %}root{% else %}relrod{% endif %}"
  sudo: "{% if cloud == 'true' %}yes{% else %}no{% endif %}"
  sudo_user: root

- name: Deploy NRPE
  hosts: "{{ target }}"
  user: "{% if cloud == 'true' %}root{% else %}relrod{% endif %}"
  sudo: "{% if cloud == 'true' %}yes{% else %}no{% endif %}"
  sudo_user: root

  roles:
  - fix-lenny-sources
  - nrpe-debian
