- name: Set sources.list to something sane on lenny
  copy: src=sources.list dest=/etc/apt/sources.list
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "5"

- name: Update package cache
  apt: update_cache=yes
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "5"
